### ISSUE TITLE
enable multiple admin users to talk to Apollo

### ISSUE THREAD

**Issue by Yating-L** [galaxy-genome-annotation/galaxy-tools#13]
I'd like to use your Apollo tools like create_or_update_organism to talk to Apollo. I have some questions about the authentication method. If you set admin username and password as environment variables, then there can be only one admin account used for Apollo interaction. If we want to allow multiple qualified Galaxy users to talk to Apollo, is there a way to do it? Thank you!

**Comment by erasche** [comment]
Yes, we use one admin user to manage all of the users in apollo.

> If we want to allow multiple qualified Galaxy users to talk to Apollo, is there a way to do it? Thank you!

What would be the end goal/purpose of having multiple users for the apollo interaction?

(In case it isn't clear in the tools) The current setup is multi-user, there is just one "admin" user who handles creating the organism / granting permissions to the requesting user, etc. Since all actions can be accomplished as an admin user (creating organisms, listing organisms, deleting organisms) we just do the permission validation on the galaxy side, e.g. the `list organisms` only shows organisms available to that user.

Since there are some actions that necessarily require admin permissions (due to Apollo's permission model), like creating a new organism, or adding a collaborator to that organism, I decided not to use the individual user's username/password to talk to apollo. This had the additional benefit of not needing to know the user's apollo password, we can share this one secret galaxy-apollo-admin password.

**Comment by abretaud** [comment]
On my setup, this single admin user is used by galaxy tools to create organisms.
I also have an ldap authentication (with REMOTE_USER) for real users of the apollo instance.
I grant admin access to a few other (ldap) users by using a special APOLLO_REMOTE_ADMINS docker env var which is used to bootstrap the apollo instance at startup: https://github.com/abretaud/docker-apollo/blob/bipaa/bootstrap.sh#L38
(this APOLLO_REMOTE_ADMINS is only available in my apollo docker image though)

**Comment by Yating-L** [comment]
I like the idea of only sharing one secret galaxy-apollo-admin password. 
> What would be the end goal/purpose of having multiple users for the apollo interaction?

@erasche Currently, Apollo has three types of users: admin, instructor, and user. We would like to enable instructors to interact with Apollo from Galaxy. For example, create/update/delete organisms, create users, create userGroups and etc. The galaxy-apollo-admin can do these for instructors, but may have some issues. I have some thoughts about adapting the tools for supporting the instructor role. I mainly looked at create_or_update_organism tool. 

- shall we allow normal users to interact with Apollo with the tools (like create organisms)? I assume that only admin users and instructors are allowed.  
- would the instructor/admin who creates an organism be granted administrative privilege to the organism? 
- users having write privilege can overwrite the organism. Shall we only allow users who have administrative permission to overwrite the organism?

**Comment by Yating-L** [comment]
@abretaud  If I understand correctly, the single admin user is used to create organisms, and $APOLLO_REMOTE_ADMINS is only used for creating admin users. We'd like to allow multiple admins/instructors to create organisms from Galaxy.

**Comment by abretaud** [comment]
APOLLO_REMOTE_ADMINS is only useful for users connecting to apollo without using galaxy.

I don't remember how this is coded in the galaxy tools, not sure if what you'd like to do is easily doable (and I miss time to look at it right now)

**Comment by erasche** [comment]
> Currently, Apollo has three types of users

"Currently," since 2? 3? months now. So the different permissions before definitely affected our design decisions, please bear this in mind for the discussion.

> The galaxy-apollo-admin can do these for instructors, but may have some issues

What issues are you worried about here? I'd love to hear about them. For our purposes this has never had any issues for the admin user to do all of the required tasks, so I'm curious what we might be missing.

I worry that changing the tools to use the instructor role would unnecessarily limit their ability to function. **However** if individual sites want to do that, they absolutely can, just by making the galaxy-apollo-admin an instructor role. I think this would work, it would just limit the ability of the "admin" user to see all the organisms. If a user, outside of the course, was using your apollo/galaxy setup, running the "list organisms" tool, they would not see any of their organisms if the instructor wasn't granted permissions on those organisms.

> shall we allow normal users to interact with Apollo with the tools (like create organisms)? I assume that only admin users and instructors are allowed.

In a perfect world, apollo supports OAuth2 and we can use those tokens instead and do the interactions on behalf of the requesting user. Then I could get rid of all my duplicated permission-checking logic in the galaxy apollo tools that tries to make sure the admin user only exposes data to the requesting user that they have permission for. Apollo would be the sole source of truth.

Since we don't have an amazing feature like that, yet, we built these tools with the design that a single admin user should talk to the server, and we will duplicate the permission logic to make sure users can't do things that they're not supposed to be able to do.

I do not see the future where non-admin credentials are used through the tool coming soon. I think this takes quite some time.

> would the instructor/admin who creates an organism be granted administrative privilege to the organism?

No, we did not choose to do this. 

- The 'galaxy-apollo-admin' user has access to all organisms, so there was really no purpose to grant an additional permission on that organism.
- The "admin" is really just a service account that's doing things on our behalf, it is never logged into by a human in the web interface.

So there was no point for us to make an extra permission grant since it simply wasn't necessary. If you moved to an instructor role, I'm not sure how that works, maybe it is necessary there? I've never used the instructor role.

> users having write privilege can overwrite the organism. Shall we only allow users who have administrative permission to overwrite the organism?

This was an intentional design decision and was important to my users being independent. I struggled with a good way to handle this for a long time but it came down to this:

- If the user updates the organism (pushes a new JBrowse with new track / could be a new contig as well), then they continue to access the same URL, the same organism, and they retain all of their annotations. Everything continues working, we don't have to do any versioning scheme in the name so the user knows which version is the latest. After dealing with many issues over the years in that lab of people annotating different versions, I found it important that there was only one version of the organism and users could not screw up which one it was. If they needed backups/versioning, they exported copies to track their progress.
- If we block their ability to update an organism, then an unprivileged user (the only ones who are creating these organisms, and they can only do this with a privileged admin account because apollo's permission model isn't good) can only create new organisms. What about all of their annotations? We would have to write a tool to manually copy them over to the new organism *AND* we lose all of the annotation history in creating a new annotation.

These tools primary focus was to enable students and researchers to annotate their organisms independently. I get the impression that you're running a class where only the instructor should be able to create the organisms and you're worried about students overwriting them. Is that close? If so, then surely just asking the students not to overwrite the shared organism would work?

I'm not sure what you mean by `APOLLO_REMOTE_ADMINS`.

Am I missing it? I don't remember any such feature.
https://github.com/galaxy-genome-annotation/galaxy-tools/search?utf8=%E2%9C%93&q=APOLLO_REMOTE_ADMINS&type=

> We'd like to allow multiple admins/instructors to create organisms from Galaxy.

This is the most important thing I have to say from this response: I'm really happy to hear your idea and help you implement it, but I'm afraid I'm still not understanding the why, in what ways would this produce a better experience than the existing method?

Is the concern with using an admin user? is it the privileges associated with the account? We have been very careful in how we wrote the tools so users cannot exceed their privileges. If it's a concern about someone gaining access to that account, then using a strong password and preventing coworkers from obtaining it (unless necessary) should be sufficient.

**Comment by abretaud** [comment]
> I'm not sure what you mean by APOLLO_REMOTE_ADMINS.
> Am I missing it? I don't remember any such feature.
https://github.com/galaxy-genome-annotation/galaxy-tools/search?utf8=%E2%9C%93&q=APOLLO_REMOTE_ADMINS&type=

This is a little addition I made to my apollo flavor (=bipaa branch on https://github.com/abretaud/docker-apollo) = when the container starts up I grant admin rights to a few users (authenticated using ldap). In the case they want to play with some canned values using the apollo admin interface if they want for example.

**Comment by erasche** [comment]
Oh, gotcha, nice!

**Comment by Yating-L** [comment]
Thank you very much for detailed explanation. Now I understand much better!

> These tools primary focus was to enable students and researchers to annotate their organisms independently.

We are targeting both researchers who do independent annotation and also collaborative annotation groups. Hopefully, we can combine these. The modification I proposed is to use instructor role for all independent annotators (for your use cases). The normal users have read, write, and export privilege to do annotation, but they cannot create/overwrite the organisms. And these groups of users mainly working on Apollo, so they don't need to use the Galaxy tools. 

I am working on a PR which may help clear out our proposal. I have a question on the create_or_update_organism tool, the "Grant access to a user group" not work for me. I didn't see any drop-down menu to select. Do I miss anything? Thank you!

**Comment by hexylena** [comment]
Closing, I believe their group went a different direction, and with the addition of the new `instructor` role, maybe that's potentially more useful point than admins.
